ecommerce/carts/urls.py
from django.urls import path
from .views import cart_home,cart_update,checkout_home,checkout_done_view
urlpatterns = [
    path('',cart_home,name='home'),
    path('update/',cart_update,name='update'),
    path('checkout/',checkout_home,name='checkout'),
    path('checkout/success/',checkout_done_view,name='success'),
    ]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import get_login,get_logout,get_register,guest_register_view
from ecommerce.views import home_view
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
from carts.views import cart_home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',home_view,name='home'),
    path('login/',get_login,name='login'),
    path('register/',get_register,name='register'),
    path('register/guest',guest_register_view,name='guest_register'),
    path('checkout/address/create/',checkout_address_create_view,name='checkout_address_create'),

    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),

    #path('cart/',cart_home,name='cart'),
    path('logout/',get_logout,name='logout'),
    path('products/', include(('products.urls','products'),namespace='products')),
    path('', include(('search.urls','search'),namespace='search')),
    path('cart/', include(('carts.urls','carts'),namespace='cart'))


]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/products/urls.py
from django.urls import path,re_path
from .views import (ProductListView,
                    ProductFeaturedDetailSlugView)
'''from ecommerce.views import (Product_list_view,
                             Product_detail_view,
                             ProductDetailView,
                             ProductFeaturedListView,
                             ProductFeaturedDetailView)'''

urlpatterns = [
    path('',ProductListView.as_view(),name='list'),
    re_path(r'^(?P<slug>[\w-]+)/$',ProductFeaturedDetailSlugView.as_view(),name='details'),

    ]

'''
path('products-fbv/',Product_list_view),
path('products/<int:pk>/',ProductDetailView.as_view()),
path('products-fbv/<int:id>/', Product_detail_view),
path('featured/',ProductFeaturedListView.as_view()),
path('featured/<int:pk>/',ProductFeaturedDetailView.as_view()),
'''

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
{% url 'products:list' as products_list %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
          crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    {% block stylesheet %} {% endblock %}
</head>
<body>
<div class="container">

    <!-- Main menu-->
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top ">
              <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="https://getbootstrap.com/docs/4.2/assets/brand/bootstrap-solid.svg" height="30" width="30">
                    Online shop
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                  <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'home' %}">Home
                        <span class="sr-only">(current)</span>
                      </a>
                    </li>
                    <li class="nav-item {% if request.path == products_list %} active {% endif %}">
                      <a class="nav-link" href="{% url 'products:list' %}">Products</a>
                    </li>
                    {% if request.session.cart_items %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'cart:home' %}">{{request.session.cart_items}}<i class="fas fa-shopping-cart"></i></a>
                    </li>
                    {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="www.google.com" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Dropdown link
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          {% if request.user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                          {% else %}
                            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                          {% endif %}
                          <a class="dropdown-item" href="#">Action</a>
                          <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                  </ul>
                  {% include 'search/snippets/search-form.html' %}

                </div>
              </div>
          </nav>

    {% block content %} {% endblock %}
</div>

    {% block script %} {% endblock %}

    <script src="{% static 'js/jquery-slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</body>
</html>

ecommerce/templates/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home page{% endblock %}
{% block stylesheet %} {% endblock %}
{% block content %}
<div class="container">
    <br>
    <div class="row">
        <div class="col-6">
            {{ object.title }}<br>
            {{ object.description }}<br>
            {{ object.price }}
            {{ object.timestamp }}
            <br>
            <img src="{{ object.image.url }}" height="500" width="500" class="rounded">
        </div>
        <div class="col-6">
            {% include "update-cart.html" with product=object cart=cart %}
        </div>
    </div>

</div>


{% endblock %}
{% block script %} {% endblock %}

ecommerce/templates/featured_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Featured product details</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<div class="container">
    {{ object }}
    <br>
    {{ object.title }}<br>
    {{ object.description }}<br>
    {{ object.price }}
    <br>
    <img src="{{ object.image.url }}">
</div>

</body>
</html>

ecommerce/templates/guest_register_form.html
<form action="{% url 'guest_register' %}" method="POST" class="form">
        {% csrf_token %}
  {% if next_url %}
  <input type="hidden"  name="next" value="{{ next_url }}">
  {% endif %}
  <div class="form-group">
    {{ form }}
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

ecommerce/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home page{% endblock %}
{% block stylesheet %} {% endblock %}
{% block content %}
<div class="container">
    <h1 class="text-success text-center">Welcome to home page</h1>
    <img src="{% static 'images/mi3.JPG' %}" class="d-block w-100" alt="...">
</div>

{% endblock %}
{% block script %} {% endblock %}

ecommerce/templates/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home page{% endblock %}
{% block stylesheet %} {% endblock %}
{% block content %}
<div class="row">
    {% for object in object_list %}
    <div class="card " style="width: 18rem;">
      <img src="{{ object.image.url }}" class="card-img-top" alt="Shohag" style="height:40%">
      <div class="card-body mb-0 pb-0">
        <h5 class="card-title text-danger">{{ object.title }}</h5>
        <h7 class="text text-info">{{ object.timestamp|timesince }} ago</h7>
        <p class="card-text">{{ object.description|truncatewords:10 }}</p>
        <a href="{{ object.get_absolute_url }}" class="btn btn-primary">View</a>
      </div>
    </div>
    {% endfor %}
</div>

{% endblock %}
{% block script %} {% endblock %}

ecommerce/templates/login_form.html
<form action="{% url 'login' %}" method="POST" class="form">
        {% csrf_token %}
  {% if next %}
  <input type="hidden"  name="next" value="{{ request.build_absolute_uri }}">
  {% endif %}
  <div class="form-group">
    <label >Username</label>
    <input type="text" class="form-control" id="exampleInputUsername"  placeholder="Enter Username" name="username">
  </div>
  <div class="form-group">
    <label>Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
  </div>
  <button type="submit" class="btn btn-primary">Login</button>
  <a href="{% url 'register' %}">Create new account</a>
</form>

ecommerce/templates/register_form.html
<form action="{% url 'register' %}" method="POST" class="form">
        {% csrf_token %}
  <div class="form-group">
    <label >Username</label>
    <input type="text" class="form-control" id="exampleInputUsername"  placeholder="Enter Username" name="username">
  </div>
  <div class="form-group">
    <label >Email</label>
    <input type="text" class="form-control" id="exampleInputEmail"  placeholder="Enter Email" name="email">
  </div>
  <div class="form-group">
    <label>Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password1">
  </div>
  <div class="form-group">
    <label>Password</label>
    <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Same as above password" name="password2">
  </div>
  <button type="submit" class="btn btn-primary">Sign up</button>
</form>

ecommerce/templates/update-cart.html
<form method="POST" action="{% url 'cart:update' %}" class="form-inline my-2 my-lg-0">{% csrf_token %}
    {% if in_cart %}
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <input class="form-control " type="hidden"  name="product_id" value="{{ product.id }}">
            <button class="btn btn-sm btn-success mx-3" type="submit">Remove</button>
    {% else %}
        <input class="form-control " type="hidden"  name="product_id" value="{{ product.id }}">
            {% if object in cart.products.all %}
            <button class="btn btn-success" type="submit">Remove</button>
            {% else %}
            <button class="btn btn-success" type="submit">Add</button>
            {% endif %}
    {% endif %}
</form>